// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFqDEoCFvdcIwGkhhmhmM3avKPRJPGqXY',
    appId: '1:688406841143:web:b06d9cfec9b5b53efb3cb2',
    messagingSenderId: '688406841143',
    projectId: 'reditclone-61aef',
    authDomain: 'reditclone-61aef.firebaseapp.com',
    storageBucket: 'reditclone-61aef.appspot.com',
    measurementId: 'G-VX7T7XYY3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBSOFfi_V8jCzI4esucExcQ9MW0_KdA5c',
    appId: '1:688406841143:android:a0be5a2da814cf3cfb3cb2',
    messagingSenderId: '688406841143',
    projectId: 'reditclone-61aef',
    storageBucket: 'reditclone-61aef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjlPjqKLsGp27QnqZw-n5gHWIVus_iiU8',
    appId: '1:688406841143:ios:bd0142839214e382fb3cb2',
    messagingSenderId: '688406841143',
    projectId: 'reditclone-61aef',
    storageBucket: 'reditclone-61aef.appspot.com',
    iosBundleId: 'com.example.redditcloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjlPjqKLsGp27QnqZw-n5gHWIVus_iiU8',
    appId: '1:688406841143:ios:bd0142839214e382fb3cb2',
    messagingSenderId: '688406841143',
    projectId: 'reditclone-61aef',
    storageBucket: 'reditclone-61aef.appspot.com',
    iosBundleId: 'com.example.redditcloneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFqDEoCFvdcIwGkhhmhmM3avKPRJPGqXY',
    appId: '1:688406841143:web:23a63110aca9ccbffb3cb2',
    messagingSenderId: '688406841143',
    projectId: 'reditclone-61aef',
    authDomain: 'reditclone-61aef.firebaseapp.com',
    storageBucket: 'reditclone-61aef.appspot.com',
    measurementId: 'G-4MM7LBWPF1',
  );
}
